#Project Metadata
site_name: RHoA Docs
site_description: 'Documentation on different platforms, builds, information necessary and informative on Planteside 2 gameplay'
copyright: 'Copyright &copy; 2020 RHoA'

# Where things are
# encoding: UTF-8
plugins_dir: _plugins
layouts: _layouts
data_dir: _data
theme: jekyll-theme-modernist

# theme:
#   favicon: '_data/icons/favicon.ico'
#   language: 'en'
#   logo: '_data/images/logo.svg'
  
# Social Accounts:
extra: 
  social:
    - type: 'discord'
      link: 'https://discord.gg/WBrZVHs'
    - type: 'github'
      link: 'https://gitub.com/kajov'

  
nav:
- Overview: 'index.md'
- Structure menu:
  What is RHoA?: 'about/rhoa.md'